// svelte/lib/components/AiohaProvider.svelte
<script lang="ts">
  import { onMount, setContext } from 'svelte'
  import type { Aioha } from '@aioha/aioha'
  import { AiohaCtxKey } from '../context.js'

  const { aioha, children }: { aioha: Aioha; children: any } = $props()

  let ctx = $state({
    aioha: aioha,
    user: aioha.getCurrentUser(),
    provider: aioha.getCurrentProvider(),
    otherUsers: aioha.getOtherLogins()
  })

  const update = () => {
    ctx.user = aioha.getCurrentUser()
    ctx.provider = aioha.getCurrentProvider()
    ctx.otherUsers = aioha.getOtherLogins()
  }

  onMount(() => {
    aioha.on('connect', update)
    aioha.on('disconnect', update)
    aioha.on('account_changed', update)

    return () => {
      aioha.off('connect', update)
      aioha.off('disconnect', update)
      aioha.off('account_changed', update)
    }
  })

  setContext(AiohaCtxKey, ctx)
</script>

{@render children()}

// vue/lib/components/AiohaProvider.vue
<script setup lang="ts">
import { provide, ref, onMounted, onUnmounted } from 'vue'
import { Aioha, Providers, PersistentLoginProvs } from '@aioha/aioha'
import { AiohaContextKey } from '../composables/context.js'

// Props interface
interface Props {
  aioha: Aioha
}

const props = defineProps<Props>()

// Reactive state
const user = ref<string | undefined>(props.aioha.getCurrentUser())
const provider = ref<Providers | undefined>(props.aioha.getCurrentProvider())
const otherUsers = ref<PersistentLoginProvs>(props.aioha.getOtherLogins())

// Update function
const update = () => {
  user.value = props.aioha.getCurrentUser()
  provider.value = props.aioha.getCurrentProvider()
  otherUsers.value = props.aioha.getOtherLogins()
}

// Setup event listeners
onMounted(() => {
  props.aioha.on('connect', update)
  props.aioha.on('disconnect', update)
  props.aioha.on('account_changed', update)
})

onUnmounted(() => {
  props.aioha.off('connect', update)
  props.aioha.off('disconnect', update)
  props.aioha.off('account_changed', update)
})

// Provide the context
provide(AiohaContextKey, {
  aioha: props.aioha,
  user: user.value,
  provider: provider.value,
  otherUsers: otherUsers.value
})
</script>

<template>
  <slot></slot>
</template>
