// magi/svelte/lib/components/MagiProvider.svelte
<script lang="ts">
  import { onMount, setContext } from 'svelte'
  import type { Aioha } from '@aioha/aioha'
  import type { Magi } from '@aioha/magi'
  import { Wallet } from '@aioha/magi'
  import { MagiCtxKey, type EIP1193Provider } from '../context.js'

  const { magi, aioha, eip1193, children }: { magi: Magi; aioha?: Aioha; eip1193?: EIP1193Provider; children: any } = $props()

  let ctx = $state({
    magi: magi,
    user: magi.getUser(),
    wallet: magi.getWallet()
  })

  const update = () => {
    ctx.user = magi.getUser()
    ctx.wallet = magi.getWallet()
  }

  const updateHive = () => {
    if (magi.getWallet() === Wallet.Hive) ctx.user = magi.getUser()
  }

  const updateEvm = () => {
    if (magi.getWallet() === Wallet.Ethereum) ctx.user = magi.getUser()
  }

  onMount(() => {
    magi.on('wallet_changed', update)
    if (aioha) {
      aioha.on('connect', updateHive)
      aioha.on('disconnect', updateHive)
      aioha.on('account_changed', updateHive)
    }
    if (eip1193) {
      eip1193.on('accountsChanged', updateEvm)
    }

    return () => {
      magi.off('wallet_changed', update)
      if (aioha) {
        aioha.off('connect', updateHive)
        aioha.off('disconnect', updateHive)
        aioha.off('account_changed', updateHive)
      }
      if (eip1193) {
        eip1193.removeListener('accountsChanged', updateEvm)
      }
    }
  })

  setContext(MagiCtxKey, ctx)
</script>

{@render children()}

// magi/vue/lib/components/MagiProvider.vue
<script setup lang="ts">
import { provide, ref, onMounted, onUnmounted } from 'vue'
import { Magi, Wallet } from '@aioha/magi'
import type { Aioha } from '@aioha/aioha'
import { MagiCtx, MagiUserCtx, MagiWalletCtx } from '../composables/context.js'
import type { EIP1193Provider } from '../../../types.js'

interface Props {
  magi: Magi
  aioha?: Aioha
  eip1193?: EIP1193Provider
}

const props = defineProps<Props>()

// Reactive state
const user = ref<string | undefined>(props.magi.getUser())
const wallet = ref<Wallet | undefined>(props.magi.getWallet())

// Update functions
const update = () => {
  user.value = props.magi.getUser()
  wallet.value = props.magi.getWallet()
}

const updateHive = () => {
  if (props.magi.getWallet() === Wallet.Hive) user.value = props.magi.getUser()
}

const updateEvm = () => {
  if (props.magi.getWallet() === Wallet.Ethereum) user.value = props.magi.getUser()
}

// Setup event listeners
onMounted(() => {
  props.magi.on('wallet_changed', update)
  if (props.aioha) {
    props.aioha.on('connect', updateHive)
    props.aioha.on('disconnect', updateHive)
    props.aioha.on('account_changed', updateHive)
  }
  if (props.eip1193) {
    props.eip1193.on('accountsChanged', updateEvm)
  }
})

onUnmounted(() => {
  props.magi.off('wallet_changed', update)
  if (props.aioha) {
    props.aioha.off('connect', updateHive)
    props.aioha.off('disconnect', updateHive)
    props.aioha.off('account_changed', updateHive)
  }
  if (props.eip1193) {
    props.eip1193.removeListener('accountsChanged', updateEvm)
  }
})

// Provide the context
provide(MagiCtx, props.magi)
provide(MagiUserCtx, user)
provide(MagiWalletCtx, wallet)
</script>

<template>
  <slot></slot>
</template>
